services:
  whois-domain-lookup:
    container_name: whois-domain-lookup
    image: reg233/whois-domain-lookup:latest
    environment:
      DATA_SOURCE: "all"
      DEFAULT_EXTENSION: ""
      BASE: "/"
      HOSTED_ON: ""
      HOSTED_ON_URL: ""
    restart: unless-stopped
    ports:
      - "10001:80"
